[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Harry Wright <harry@wright.dev>"]

[tool.poetry.dependencies]
python = "^3.8.6"
numpy = "^1.19.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
